// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: operation/v1/operation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 题目内容
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// 知识点
	Knowledge int32 `protobuf:"varint,2,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
}

func (x *OperateRequest) Reset() {
	*x = OperateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operation_v1_operation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateRequest) ProtoMessage() {}

func (x *OperateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_operation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateRequest.ProtoReflect.Descriptor instead.
func (*OperateRequest) Descriptor() ([]byte, []int) {
	return file_operation_v1_operation_proto_rawDescGZIP(), []int{0}
}

func (x *OperateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *OperateRequest) GetKnowledge() int32 {
	if x != nil {
		return x.Knowledge
	}
	return 0
}

type OperateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 答案
	Solution string `protobuf:"bytes,2,opt,name=solution,proto3" json:"solution,omitempty"`
	// 步骤列表
	Steps []*OperateReply_Step `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *OperateReply) Reset() {
	*x = OperateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operation_v1_operation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateReply) ProtoMessage() {}

func (x *OperateReply) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_operation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateReply.ProtoReflect.Descriptor instead.
func (*OperateReply) Descriptor() ([]byte, []int) {
	return file_operation_v1_operation_proto_rawDescGZIP(), []int{1}
}

func (x *OperateReply) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *OperateReply) GetSteps() []*OperateReply_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

// 步骤
type OperateReply_Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 步骤名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 步骤结果
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *OperateReply_Step) Reset() {
	*x = OperateReply_Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operation_v1_operation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateReply_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateReply_Step) ProtoMessage() {}

func (x *OperateReply_Step) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_operation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateReply_Step.ProtoReflect.Descriptor instead.
func (*OperateReply_Step) Descriptor() ([]byte, []int) {
	return file_operation_v1_operation_proto_rawDescGZIP(), []int{1, 0}
}

func (x *OperateReply_Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperateReply_Step) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_operation_v1_operation_proto protoreflect.FileDescriptor

var file_operation_v1_operation_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x48, 0x0a, 0x0e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x0c, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x53,
	0x74, 0x65, 0x70, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x1a, 0x32, 0x0a, 0x04, 0x53, 0x74,
	0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0x52,
	0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x07, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_operation_v1_operation_proto_rawDescOnce sync.Once
	file_operation_v1_operation_proto_rawDescData = file_operation_v1_operation_proto_rawDesc
)

func file_operation_v1_operation_proto_rawDescGZIP() []byte {
	file_operation_v1_operation_proto_rawDescOnce.Do(func() {
		file_operation_v1_operation_proto_rawDescData = protoimpl.X.CompressGZIP(file_operation_v1_operation_proto_rawDescData)
	})
	return file_operation_v1_operation_proto_rawDescData
}

var file_operation_v1_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_operation_v1_operation_proto_goTypes = []interface{}{
	(*OperateRequest)(nil),    // 0: operation.v1.OperateRequest
	(*OperateReply)(nil),      // 1: operation.v1.OperateReply
	(*OperateReply_Step)(nil), // 2: operation.v1.OperateReply.Step
}
var file_operation_v1_operation_proto_depIdxs = []int32{
	2, // 0: operation.v1.OperateReply.steps:type_name -> operation.v1.OperateReply.Step
	0, // 1: operation.v1.Operation.Operate:input_type -> operation.v1.OperateRequest
	1, // 2: operation.v1.Operation.Operate:output_type -> operation.v1.OperateReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_operation_v1_operation_proto_init() }
func file_operation_v1_operation_proto_init() {
	if File_operation_v1_operation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_operation_v1_operation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operation_v1_operation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operation_v1_operation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateReply_Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_operation_v1_operation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operation_v1_operation_proto_goTypes,
		DependencyIndexes: file_operation_v1_operation_proto_depIdxs,
		MessageInfos:      file_operation_v1_operation_proto_msgTypes,
	}.Build()
	File_operation_v1_operation_proto = out.File
	file_operation_v1_operation_proto_rawDesc = nil
	file_operation_v1_operation_proto_goTypes = nil
	file_operation_v1_operation_proto_depIdxs = nil
}
