// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: search/v1/solve.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchQuestionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 题目图片链接
	FileUrl string `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
}

func (x *SearchQuestionRequest) Reset() {
	*x = SearchQuestionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_v1_solve_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionRequest) ProtoMessage() {}

func (x *SearchQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_solve_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionRequest.ProtoReflect.Descriptor instead.
func (*SearchQuestionRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_solve_proto_rawDescGZIP(), []int{0}
}

func (x *SearchQuestionRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type SearchQuestionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 搜索结果
	DetailSolution string `protobuf:"bytes,1,opt,name=detail_solution,json=detailSolution,proto3" json:"detail_solution,omitempty"`
}

func (x *SearchQuestionReply) Reset() {
	*x = SearchQuestionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_v1_solve_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchQuestionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionReply) ProtoMessage() {}

func (x *SearchQuestionReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_solve_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionReply.ProtoReflect.Descriptor instead.
func (*SearchQuestionReply) Descriptor() ([]byte, []int) {
	return file_search_v1_solve_proto_rawDescGZIP(), []int{1}
}

func (x *SearchQuestionReply) GetDetailSolution() string {
	if x != nil {
		return x.DetailSolution
	}
	return ""
}

var File_search_v1_solve_proto protoreflect.FileDescriptor

var file_search_v1_solve_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e,
	0x76, 0x31, 0x22, 0x32, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66,
	0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x3e, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a,
	0x0f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x5e, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x54, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_search_v1_solve_proto_rawDescOnce sync.Once
	file_search_v1_solve_proto_rawDescData = file_search_v1_solve_proto_rawDesc
)

func file_search_v1_solve_proto_rawDescGZIP() []byte {
	file_search_v1_solve_proto_rawDescOnce.Do(func() {
		file_search_v1_solve_proto_rawDescData = protoimpl.X.CompressGZIP(file_search_v1_solve_proto_rawDescData)
	})
	return file_search_v1_solve_proto_rawDescData
}

var file_search_v1_solve_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_search_v1_solve_proto_goTypes = []interface{}{
	(*SearchQuestionRequest)(nil), // 0: search.v1.SearchQuestionRequest
	(*SearchQuestionReply)(nil),   // 1: search.v1.SearchQuestionReply
}
var file_search_v1_solve_proto_depIdxs = []int32{
	0, // 0: search.v1.Search.SearchQuestion:input_type -> search.v1.SearchQuestionRequest
	1, // 1: search.v1.Search.SearchQuestion:output_type -> search.v1.SearchQuestionReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_search_v1_solve_proto_init() }
func file_search_v1_solve_proto_init() {
	if File_search_v1_solve_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_search_v1_solve_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchQuestionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_v1_solve_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchQuestionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_search_v1_solve_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_solve_proto_goTypes,
		DependencyIndexes: file_search_v1_solve_proto_depIdxs,
		MessageInfos:      file_search_v1_solve_proto_msgTypes,
	}.Build()
	File_search_v1_solve_proto = out.File
	file_search_v1_solve_proto_rawDesc = nil
	file_search_v1_solve_proto_goTypes = nil
	file_search_v1_solve_proto_depIdxs = nil
}
