// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: parse/v1/parse.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseQuestionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 题目内容
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// 题目图片链接
	FileUrl string `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
}

func (x *ParseQuestionRequest) Reset() {
	*x = ParseQuestionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parse_v1_parse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseQuestionRequest) ProtoMessage() {}

func (x *ParseQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parse_v1_parse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseQuestionRequest.ProtoReflect.Descriptor instead.
func (*ParseQuestionRequest) Descriptor() ([]byte, []int) {
	return file_parse_v1_parse_proto_rawDescGZIP(), []int{0}
}

func (x *ParseQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ParseQuestionRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type ParseQuestionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 题目内容
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// 知识点
	Knowledge int32 `protobuf:"varint,2,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
}

func (x *ParseQuestionReply) Reset() {
	*x = ParseQuestionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parse_v1_parse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseQuestionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseQuestionReply) ProtoMessage() {}

func (x *ParseQuestionReply) ProtoReflect() protoreflect.Message {
	mi := &file_parse_v1_parse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseQuestionReply.ProtoReflect.Descriptor instead.
func (*ParseQuestionReply) Descriptor() ([]byte, []int) {
	return file_parse_v1_parse_proto_rawDescGZIP(), []int{1}
}

func (x *ParseQuestionReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ParseQuestionReply) GetKnowledge() int32 {
	if x != nil {
		return x.Knowledge
	}
	return 0
}

var File_parse_v1_parse_proto protoreflect.FileDescriptor

var file_parse_v1_parse_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x61, 0x72, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x61, 0x72, 0x73, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x4b, 0x0a, 0x14, 0x50, 0x61, 0x72, 0x73, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x4c, 0x0a,
	0x12, 0x50, 0x61, 0x72, 0x73, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x32, 0x58, 0x0a, 0x05, 0x50,
	0x61, 0x72, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x73, 0x65, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parse_v1_parse_proto_rawDescOnce sync.Once
	file_parse_v1_parse_proto_rawDescData = file_parse_v1_parse_proto_rawDesc
)

func file_parse_v1_parse_proto_rawDescGZIP() []byte {
	file_parse_v1_parse_proto_rawDescOnce.Do(func() {
		file_parse_v1_parse_proto_rawDescData = protoimpl.X.CompressGZIP(file_parse_v1_parse_proto_rawDescData)
	})
	return file_parse_v1_parse_proto_rawDescData
}

var file_parse_v1_parse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_parse_v1_parse_proto_goTypes = []interface{}{
	(*ParseQuestionRequest)(nil), // 0: parse.v1.ParseQuestionRequest
	(*ParseQuestionReply)(nil),   // 1: parse.v1.ParseQuestionReply
}
var file_parse_v1_parse_proto_depIdxs = []int32{
	0, // 0: parse.v1.Parse.ParseQuestion:input_type -> parse.v1.ParseQuestionRequest
	1, // 1: parse.v1.Parse.ParseQuestion:output_type -> parse.v1.ParseQuestionReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parse_v1_parse_proto_init() }
func file_parse_v1_parse_proto_init() {
	if File_parse_v1_parse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parse_v1_parse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseQuestionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parse_v1_parse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseQuestionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parse_v1_parse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parse_v1_parse_proto_goTypes,
		DependencyIndexes: file_parse_v1_parse_proto_depIdxs,
		MessageInfos:      file_parse_v1_parse_proto_msgTypes,
	}.Build()
	File_parse_v1_parse_proto = out.File
	file_parse_v1_parse_proto_rawDesc = nil
	file_parse_v1_parse_proto_goTypes = nil
	file_parse_v1_parse_proto_depIdxs = nil
}
