// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/ninely/go-work/final/app/bff/homework/internal/biz"
	"github.com/ninely/go-work/final/app/bff/homework/internal/conf"
	"github.com/ninely/go-work/final/app/bff/homework/internal/data"
	"github.com/ninely/go-work/final/app/bff/homework/internal/server"
	"github.com/ninely/go-work/final/app/bff/homework/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	homeworkRepo := data.NewHomeworkRepo(dataData, logger)
	homeworkUseCase := biz.NewHomeworkUseCase(homeworkRepo, logger)
	homeworkService := service.NewHomeworkService(homeworkUseCase)
	httpServer := server.NewHTTPServer(confServer, homeworkService, logger)
	grpcServer := server.NewGRPCServer(confServer, homeworkService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
